engines:
  fixme:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true

checks:
  identical-code:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: 5

ratings:
  paths:
    - "**.go"

exclude_paths:
  - "**/vendor/**/*"
  - "**/*_test.go"
