engines:
  fixme:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true

ratings:
  paths:
    - "**.go"

exclude_paths:
  - "**/vendor/**/*"
  - "**_test.go"
