package completion

const bashCompletionFunctionDefinition string = `
# Pre-defined variables
#
# COMP_LINE : The current command line.
# COMP_WORDS: An array variable consisting of the individual words in the current command line, ${COMP_LINE}.
# COMP_CWORD: An index into ${COMP_WORDS} of the word containing the current cursor position.
# COMPREPLY : An array variable from which bash reads the possible completions generated by a completion function.

_{{.AppName}}()
{
}
complete -F _{{.AppName}} {{.AppName}}
`