package completion

const bashCompletionTemplate string = `
# Pre-defined variables
#
# COMP_LINE : The current command line.
# COMP_WORDS: An array variable consisting of the individual words in the current command line, ${COMP_LINE}.
# COMP_CWORD: An index into ${COMP_WORDS} of the word containing the current cursor position.
# COMPREPLY : An array variable from which bash reads the possible completions generated by a completion function.

_{{.AppName}}()
{
    local current_word prev_word commands_0 flags
    current_word=${COMP_WORDS[COMP_CWORD]}
    prev_word=${COMP_WORDS[COMP_CWORD-1]}

    case ${COMP_CWORD} in
        1)
            COMPREPLY=($(compgen -W "{{range $index, $rootCmd := .RootCommands}}{{if $index}} {{end}}{{$rootCmd}}{{end}}" -- ${current_word}))
            ;;
        *)
            case ${prev_word} in{{range $parent, $children := .ParentVsDirectChildren}}
                {{if $children}}{{$parent}})
                    COMPREPLY=($(compgen -W "{{range $index, $child := $children}}{{if $index}} {{end}}{{$child}}{{end}}" -- ${current_word}))
                    ;;{{end}}{{end}}
                *)
                    COMPREPLY=()
                    ;;
            esac
            ;;
    esac

}
complete -F _{{.AppName}} {{.AppName}}
`
