package cmd

import (
	"os"
	"time"

	"github.com/bpicode/fritzctl/man"
	"github.com/spf13/cobra"
)

var docManCmd = &cobra.Command{
	Use:     "man",
	Short:   "Man page for this application",
	Long:    "Generate the man page(s) for this application.",
	Example: "fritzctl doc man | man /dev/stdin",
	RunE:    docMan,
}

func init() {
	docCmd.AddCommand(docManCmd)
}

func docMan(cmd *cobra.Command, args []string) error {
	err := man.GenerateManPage(RootCmd, &man.Options{
		Title:   "fritzctl",
		Section: "1",
		Source:  "Auto-generated by bpicode/fritzctl",
		Manual:  "fritzctl man page",
		Date:    time.Now(),
		SeeAlso: []string{"kfritz(1)", "curl(1)"},
	}, os.Stdout)
	return err
}
